---
- hosts: all
  become: true
  tasks:
  - name: install docker
    apt:
      pkg: docker.io
      state: present
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
  - name: deploy  application
    command: sudo docker run -it -d -p 8081:8888 priyankoudagani/test:2.0
  handlers:
  - name: run update
    apt:
      update_cache: yes
...
